/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-08-29 11:20:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.nurse;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class create_002dnurse_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005fmethod_005fcommandName_005fclass_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005frequired_005fpattern_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fradiobutton_0026_005fvalue_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005fpattern_005fpath_005fautocomplete_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpattern_005fpath_005fautocomplete_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpattern_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005frequired_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fpassword_0026_005frequired_005fpath_005fid_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005fpattern_005fpath_005fautocomplete_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmethod_005fcommandName_005fclass_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005frequired_005fpattern_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005fradiobutton_0026_005fvalue_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005fpattern_005fpath_005fautocomplete_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpattern_005fpath_005fautocomplete_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpattern_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005frequired_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005fpassword_0026_005frequired_005fpath_005fid_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005fpattern_005fpath_005fautocomplete_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmethod_005fcommandName_005fclass_005faction.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005frequired_005fpattern_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005fradiobutton_0026_005fvalue_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005fpattern_005fpath_005fautocomplete_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpattern_005fpath_005fautocomplete_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpattern_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005frequired_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005fpassword_0026_005frequired_005fpath_005fid_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005fpattern_005fpath_005fautocomplete_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Create Nurse</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/reset.css\" type=\"text/css\">\r\n");
      out.write("\t<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>\t\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"resources/css/template.css\" type=\"text/css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"resources/css/forms.css\" type=\"text/css\">\t\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"resources/css/form-popup.css\" type=\"text/css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"resources/css/template-table.css\" type=\"text/css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"resources/css/homepage.css\" type=\"text/css\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<link rel=\"stylesheet\" media=\"all\" href=\"resources/css/jsDatePick_ltr.min.css\" type=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("window.onload = function(){\r\n");
      out.write("\tnew JsDatePick({\r\n");
      out.write("\t\tuseMode:2,\r\n");
      out.write("\t\ttarget:\"inputField\",\r\n");
      out.write("\t\tdateFormat:\"%Y-%m-%d\"\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("\t\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"wrap\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../headers/admin-header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Create Nurse", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("selected", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("nurses", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"content-wrap\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t\t<div class=\"tabs\">\r\n");
      out.write("\t\t\t<div class=\"tab-content\">\r\n");
      out.write("\t\t\t\t<div id=\"History\" class=\"tab active\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t<!-- class=\"crmForm\" -->\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_form_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end wrapper-->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- end content-wrap-->\r\n");
      out.write("<footer>\t\r\n");
      out.write("\t<span class=\"copy\"><a href=\"\">&copy; 2014 Pendragons</a></span>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"resources/js/jquery.1.4.2.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"resources/js/jsDatePick.jquery.min.1.3.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"resources/js/jquery-1.9.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"resources/js/scripts.js\"></script>\r\n");
      out.write("\t<script src=\"resources/js/retypepwd.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_form_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fmethod_005fcommandName_005fclass_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
    _jspx_th_form_005fform_005f0.setParent(null);
    // /WEB-INF/jsp/nurse/create-nurse.jsp(51,6) null
    _jspx_th_form_005fform_005f0.setDynamicAttribute(null, "class", "crmForm");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(51,6) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setMethod("post");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(51,6) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setCommandName("nurse");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(51,6) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setAction((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("create_nurse.it?adminId=${adminUser.getId() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
      if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<section>\r\n");
          out.write("\t\t\t\t\t\t\t\t<header>\r\n");
          out.write("\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<h3>Nurse Information</h3>\r\n");
          out.write("\t\t\t\t\t\t\t\t</header>\r\n");
          out.write("\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t<ul class=\"fields\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><label>First Name<span style=\"color:red;\">*</span> </label>:");
          if (_jspx_meth_form_005finput_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><label>Last Name<span style=\"color:red;\">*</span></label>:");
          if (_jspx_meth_form_005finput_005f1(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><label>License Number<span style=\"color:red;\">*</span></label>:");
          if (_jspx_meth_form_005finput_005f2(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><label>Occupation</label>:");
          if (_jspx_meth_form_005finput_005f3(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><label>Date of Birth<span style=\"color:red;\">*</span></label>:<input name=\"dateOfBirth\" type=\"text\" required id=\"inputField\" readonly/></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><label>Gender</label>:\r\n");
          out.write("\t\t\t\t\t\t\t\t\t   <label>Male</label>");
          if (_jspx_meth_form_005fradiobutton_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<label>Female</Label>");
          if (_jspx_meth_form_005fradiobutton_005f1(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><label>Phone Number</label>:");
          if (_jspx_meth_form_005finput_005f4(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><label>Mobile Number<span style=\"color:red;\">*</span></label>");
          if (_jspx_meth_form_005finput_005f5(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><label>E-mail Address<span style=\"color:red;\">*</span></label>");
          if (_jspx_meth_form_005finput_005f6(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><label>Employee ID<span style=\"color:red;\">*</span></label>");
          if (_jspx_meth_form_005finput_005f7(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("</li>\r\n");
          out.write("\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t</section>\r\n");
          out.write("\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t<section>\r\n");
          out.write("\t\t\t\t\t\t\t<header><h3>Address</h3></header>\r\n");
          out.write("\t\t\t\t\t\t\t<ul class=\"fields\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><label>Address</label>:");
          if (_jspx_meth_form_005finput_005f8(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><label>City</label>:");
          if (_jspx_meth_form_005finput_005f9(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><label>Province</label>:");
          if (_jspx_meth_form_005finput_005f10(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><label>Zip Code</label>:");
          if (_jspx_meth_form_005finput_005f11(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("</li>\r\n");
          out.write("\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t</section>\r\n");
          out.write("\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t<section>\r\n");
          out.write("\t\t\t\t\t\t\t<header><h3>Account Details</h3></header>\r\n");
          out.write("\t\t\t\t\t\t\t<ul class=\"fields\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><label>Username<span style=\"color:red;\">*</span></label>");
          if (_jspx_meth_form_005finput_005f12(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><label>Password<span style=\"color:red;\">*</span></label>");
          if (_jspx_meth_form_005fpassword_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><label>Confirm Password<span style=\"color:red;\">*</span></label><input type=\"password\" required=\"true\" id=\"txtConfirmPassword\" onChange=\"isPasswordMatch();\" /></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><div id=\"divCheckPassword\" style=\"color:red\"></div></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><span style=\"color:red;\">* The purpose of the following fields is to validate your account for resetting your password to your birthday.</span><li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><label>Security Question<span style=\"color:red;\">*</span></label>:");
          if (_jspx_meth_form_005finput_005f13(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><label>Answer<span style=\"color:red;\">*</span></label>:");
          if (_jspx_meth_form_005finput_005f14(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t</section>\r\n");
          out.write("\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t<section>\r\n");
          out.write("\t\t\t\t\t\t\t<header>\r\n");
          out.write("\t\t\t\t\t\t\t\t<h3>Hospital Details</h3>\r\n");
          out.write("\t\t\t\t\t\t\t</header>\r\n");
          out.write("\t\t\t\t\t\t\t<ul class=\"fields\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><label>Name</label>:");
          if (_jspx_meth_form_005finput_005f15(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><label>Phone Number</label>:");
          if (_jspx_meth_form_005finput_005f16(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><label>Work Mobile Number</label>:");
          if (_jspx_meth_form_005finput_005f17(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><label>Address</label>:");
          if (_jspx_meth_form_005finput_005f18(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><label>City</label>:");
          if (_jspx_meth_form_005finput_005f19(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><label>Province</label>:");
          if (_jspx_meth_form_005finput_005f20(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("</li>\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><label>Zip Code</label>:");
          if (_jspx_meth_form_005finput_005f21(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t</section>\t\r\n");
          out.write("\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t<br><br><br><br>\r\n");
          out.write("\t\t\t\t\t\t\t\t<section>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<ul class=\"btnForm\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<li><span class=\"btn\"><input type=\"submit\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"Create Account\" class=\"btnSave\"></span></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"view_nurses.it\"><span class=\"btn\"><input type=\"button\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"Cancel\" class=\"btnCancel\"></span></a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<div class=\"backontop\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"btn\"><input type=\"button\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"Back to Top\" class=\"btnTop\"></span>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t</section>\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005fform_005f0.doFinally();
      _005fjspx_005ftagPool_005fform_005fform_0026_005fmethod_005fcommandName_005fclass_005faction.reuse(_jspx_th_form_005fform_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f0.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/jsp/nurse/create-nurse.jsp(59,72) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f0.setPath("personInfo.firstName");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(59,72) null
    _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "type", "text");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(59,72) null
    _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "required", "true");
    int[] _jspx_push_body_count_form_005finput_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f0 = _jspx_th_form_005finput_005f0.doStartTag();
      if (_jspx_th_form_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f0.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fnobody.reuse(_jspx_th_form_005finput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f1 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f1.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/jsp/nurse/create-nurse.jsp(60,70) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f1.setPath("personInfo.lastName");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(60,70) null
    _jspx_th_form_005finput_005f1.setDynamicAttribute(null, "type", "text");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(60,70) null
    _jspx_th_form_005finput_005f1.setDynamicAttribute(null, "required", "true");
    int[] _jspx_push_body_count_form_005finput_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f1 = _jspx_th_form_005finput_005f1.doStartTag();
      if (_jspx_th_form_005finput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f1.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fnobody.reuse(_jspx_th_form_005finput_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f2 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005frequired_005fpattern_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f2.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/jsp/nurse/create-nurse.jsp(61,75) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f2.setPath("licenseNumber");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(61,75) null
    _jspx_th_form_005finput_005f2.setDynamicAttribute(null, "required", "true");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(61,75) null
    _jspx_th_form_005finput_005f2.setDynamicAttribute(null, "pattern", "(^\\+?[\\d]+(\\-?[\\d]+)*)*");
    int[] _jspx_push_body_count_form_005finput_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f2 = _jspx_th_form_005finput_005f2.doStartTag();
      if (_jspx_th_form_005finput_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f2.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005frequired_005fpattern_005fpath_005fnobody.reuse(_jspx_th_form_005finput_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f3 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f3.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/jsp/nurse/create-nurse.jsp(62,38) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f3.setPath("personInfo.occupation");
    int[] _jspx_push_body_count_form_005finput_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f3 = _jspx_th_form_005finput_005f3.doStartTag();
      if (_jspx_th_form_005finput_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f3.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fpath_005fnobody.reuse(_jspx_th_form_005finput_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_form_005fradiobutton_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:radiobutton
    org.springframework.web.servlet.tags.form.RadioButtonTag _jspx_th_form_005fradiobutton_005f0 = (org.springframework.web.servlet.tags.form.RadioButtonTag) _005fjspx_005ftagPool_005fform_005fradiobutton_0026_005fvalue_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.RadioButtonTag.class);
    _jspx_th_form_005fradiobutton_005f0.setPageContext(_jspx_page_context);
    _jspx_th_form_005fradiobutton_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/jsp/nurse/create-nurse.jsp(65,31) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fradiobutton_005f0.setPath("personInfo.sex");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(65,31) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fradiobutton_005f0.setValue("male");
    int[] _jspx_push_body_count_form_005fradiobutton_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_form_005fradiobutton_005f0 = _jspx_th_form_005fradiobutton_005f0.doStartTag();
      if (_jspx_th_form_005fradiobutton_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005fradiobutton_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005fradiobutton_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005fradiobutton_005f0.doFinally();
      _005fjspx_005ftagPool_005fform_005fradiobutton_0026_005fvalue_005fpath_005fnobody.reuse(_jspx_th_form_005fradiobutton_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_form_005fradiobutton_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:radiobutton
    org.springframework.web.servlet.tags.form.RadioButtonTag _jspx_th_form_005fradiobutton_005f1 = (org.springframework.web.servlet.tags.form.RadioButtonTag) _005fjspx_005ftagPool_005fform_005fradiobutton_0026_005fvalue_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.RadioButtonTag.class);
    _jspx_th_form_005fradiobutton_005f1.setPageContext(_jspx_page_context);
    _jspx_th_form_005fradiobutton_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/jsp/nurse/create-nurse.jsp(66,31) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fradiobutton_005f1.setPath("personInfo.sex");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(66,31) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fradiobutton_005f1.setValue("female");
    int[] _jspx_push_body_count_form_005fradiobutton_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_form_005fradiobutton_005f1 = _jspx_th_form_005fradiobutton_005f1.doStartTag();
      if (_jspx_th_form_005fradiobutton_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005fradiobutton_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005fradiobutton_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005fradiobutton_005f1.doFinally();
      _005fjspx_005ftagPool_005fform_005fradiobutton_0026_005fvalue_005fpath_005fnobody.reuse(_jspx_th_form_005fradiobutton_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f4 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fpattern_005fpath_005fautocomplete_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f4.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/jsp/nurse/create-nurse.jsp(68,40) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f4.setPath("personInfo.contacts[0].phoneNumber");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(68,40) null
    _jspx_th_form_005finput_005f4.setDynamicAttribute(null, "pattern", "(^\\+?[\\d]+(\\-?[\\d]+)*)*");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(68,40) name = autocomplete type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f4.setAutocomplete("off");
    int[] _jspx_push_body_count_form_005finput_005f4 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f4 = _jspx_th_form_005finput_005f4.doStartTag();
      if (_jspx_th_form_005finput_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f4[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f4.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f4.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fpattern_005fpath_005fautocomplete_005fnobody.reuse(_jspx_th_form_005finput_005f4);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f5 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpattern_005fpath_005fautocomplete_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f5.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/jsp/nurse/create-nurse.jsp(69,73) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f5.setPath("personInfo.contacts[0].mobileNumber");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(69,73) null
    _jspx_th_form_005finput_005f5.setDynamicAttribute(null, "type", "text");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(69,73) null
    _jspx_th_form_005finput_005f5.setDynamicAttribute(null, "required", "true");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(69,73) null
    _jspx_th_form_005finput_005f5.setDynamicAttribute(null, "pattern", "(^\\+?[\\d]+(\\-?[\\d]+)*)*");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(69,73) name = autocomplete type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f5.setAutocomplete("off");
    int[] _jspx_push_body_count_form_005finput_005f5 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f5 = _jspx_th_form_005finput_005f5.doStartTag();
      if (_jspx_th_form_005finput_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f5[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f5.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f5.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpattern_005fpath_005fautocomplete_005fnobody.reuse(_jspx_th_form_005finput_005f5);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f6 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpattern_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f6.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/jsp/nurse/create-nurse.jsp(70,74) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f6.setPath("personInfo.email");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(70,74) null
    _jspx_th_form_005finput_005f6.setDynamicAttribute(null, "type", "text");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(70,74) null
    _jspx_th_form_005finput_005f6.setDynamicAttribute(null, "required", "true");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(70,74) null
    _jspx_th_form_005finput_005f6.setDynamicAttribute(null, "pattern", "(^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,}))*");
    int[] _jspx_push_body_count_form_005finput_005f6 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f6 = _jspx_th_form_005finput_005f6.doStartTag();
      if (_jspx_th_form_005finput_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f6[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f6.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f6.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpattern_005fpath_005fnobody.reuse(_jspx_th_form_005finput_005f6);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f7 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f7.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/jsp/nurse/create-nurse.jsp(71,71) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f7.setPath("employeeId");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(71,71) null
    _jspx_th_form_005finput_005f7.setDynamicAttribute(null, "type", "text");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(71,71) null
    _jspx_th_form_005finput_005f7.setDynamicAttribute(null, "required", "true");
    int[] _jspx_push_body_count_form_005finput_005f7 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f7 = _jspx_th_form_005finput_005f7.doStartTag();
      if (_jspx_th_form_005finput_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f7[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f7.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f7.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005frequired_005fpath_005fnobody.reuse(_jspx_th_form_005finput_005f7);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f8 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f8.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/jsp/nurse/create-nurse.jsp(78,35) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f8.setPath("personInfo.addresses[0].address");
    int[] _jspx_push_body_count_form_005finput_005f8 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f8 = _jspx_th_form_005finput_005f8.doStartTag();
      if (_jspx_th_form_005finput_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f8[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f8.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f8.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fpath_005fnobody.reuse(_jspx_th_form_005finput_005f8);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f9 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f9.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/jsp/nurse/create-nurse.jsp(79,32) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f9.setPath("personInfo.addresses[0].city");
    int[] _jspx_push_body_count_form_005finput_005f9 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f9 = _jspx_th_form_005finput_005f9.doStartTag();
      if (_jspx_th_form_005finput_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f9[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f9.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f9.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fpath_005fnobody.reuse(_jspx_th_form_005finput_005f9);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f10(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f10 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f10.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/jsp/nurse/create-nurse.jsp(80,36) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f10.setPath("personInfo.addresses[0].province");
    int[] _jspx_push_body_count_form_005finput_005f10 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f10 = _jspx_th_form_005finput_005f10.doStartTag();
      if (_jspx_th_form_005finput_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f10[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f10.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f10.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fpath_005fnobody.reuse(_jspx_th_form_005finput_005f10);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f11(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f11 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f11.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f11.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/jsp/nurse/create-nurse.jsp(81,36) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f11.setPath("personInfo.addresses[0].zipCode");
    int[] _jspx_push_body_count_form_005finput_005f11 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f11 = _jspx_th_form_005finput_005f11.doStartTag();
      if (_jspx_th_form_005finput_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f11[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f11.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f11.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fpath_005fnobody.reuse(_jspx_th_form_005finput_005f11);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f12(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f12 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005frequired_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f12.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f12.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/jsp/nurse/create-nurse.jsp(89,68) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f12.setPath("user.username");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(89,68) null
    _jspx_th_form_005finput_005f12.setDynamicAttribute(null, "required", "true");
    int[] _jspx_push_body_count_form_005finput_005f12 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f12 = _jspx_th_form_005finput_005f12.doStartTag();
      if (_jspx_th_form_005finput_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f12[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f12.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f12.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005frequired_005fpath_005fnobody.reuse(_jspx_th_form_005finput_005f12);
    }
    return false;
  }

  private boolean _jspx_meth_form_005fpassword_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:password
    org.springframework.web.servlet.tags.form.PasswordInputTag _jspx_th_form_005fpassword_005f0 = (org.springframework.web.servlet.tags.form.PasswordInputTag) _005fjspx_005ftagPool_005fform_005fpassword_0026_005frequired_005fpath_005fid_005fnobody.get(org.springframework.web.servlet.tags.form.PasswordInputTag.class);
    _jspx_th_form_005fpassword_005f0.setPageContext(_jspx_page_context);
    _jspx_th_form_005fpassword_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/jsp/nurse/create-nurse.jsp(90,68) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fpassword_005f0.setPath("user.password");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(90,68) null
    _jspx_th_form_005fpassword_005f0.setDynamicAttribute(null, "required", "true");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(90,68) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fpassword_005f0.setId("txtNewPassword");
    int[] _jspx_push_body_count_form_005fpassword_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_form_005fpassword_005f0 = _jspx_th_form_005fpassword_005f0.doStartTag();
      if (_jspx_th_form_005fpassword_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005fpassword_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005fpassword_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005fpassword_005f0.doFinally();
      _005fjspx_005ftagPool_005fform_005fpassword_0026_005frequired_005fpath_005fid_005fnobody.reuse(_jspx_th_form_005fpassword_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f13(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f13 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005frequired_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f13.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f13.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/jsp/nurse/create-nurse.jsp(94,78) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f13.setPath("personInfo.securityQuestion");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(94,78) null
    _jspx_th_form_005finput_005f13.setDynamicAttribute(null, "required", "true");
    int[] _jspx_push_body_count_form_005finput_005f13 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f13 = _jspx_th_form_005finput_005f13.doStartTag();
      if (_jspx_th_form_005finput_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f13[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f13.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f13.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005frequired_005fpath_005fnobody.reuse(_jspx_th_form_005finput_005f13);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f14(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f14 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005frequired_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f14.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f14.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/jsp/nurse/create-nurse.jsp(95,67) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f14.setPath("personInfo.securityAnswer");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(95,67) null
    _jspx_th_form_005finput_005f14.setDynamicAttribute(null, "required", "true");
    int[] _jspx_push_body_count_form_005finput_005f14 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f14 = _jspx_th_form_005finput_005f14.doStartTag();
      if (_jspx_th_form_005finput_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f14[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f14.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f14.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005frequired_005fpath_005fnobody.reuse(_jspx_th_form_005finput_005f14);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f15(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f15 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f15.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f15.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/jsp/nurse/create-nurse.jsp(105,32) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f15.setPath("personInfo.companyName");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(105,32) null
    _jspx_th_form_005finput_005f15.setDynamicAttribute(null, "value", "USTH Joint and Bone Center");
    int[] _jspx_push_body_count_form_005finput_005f15 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f15 = _jspx_th_form_005finput_005f15.doStartTag();
      if (_jspx_th_form_005finput_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f15[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f15.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f15.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005fpath_005fnobody.reuse(_jspx_th_form_005finput_005f15);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f16(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f16 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005fpattern_005fpath_005fautocomplete_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f16.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f16.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/jsp/nurse/create-nurse.jsp(106,40) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f16.setPath("personInfo.contacts[1].phoneNumber");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(106,40) null
    _jspx_th_form_005finput_005f16.setDynamicAttribute(null, "value", "7313001");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(106,40) null
    _jspx_th_form_005finput_005f16.setDynamicAttribute(null, "pattern", "(^\\+?[\\d]+(\\-?[\\d]+)*)*");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(106,40) name = autocomplete type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f16.setAutocomplete("off");
    int[] _jspx_push_body_count_form_005finput_005f16 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f16 = _jspx_th_form_005finput_005f16.doStartTag();
      if (_jspx_th_form_005finput_005f16.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f16[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f16.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f16.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005fpattern_005fpath_005fautocomplete_005fnobody.reuse(_jspx_th_form_005finput_005f16);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f17(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f17 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fpattern_005fpath_005fautocomplete_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f17.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f17.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/jsp/nurse/create-nurse.jsp(107,46) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f17.setPath("personInfo.contacts[1].mobileNumber");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(107,46) null
    _jspx_th_form_005finput_005f17.setDynamicAttribute(null, "pattern", "(^\\+?[\\d]+(\\-?[\\d]+)*)*");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(107,46) name = autocomplete type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f17.setAutocomplete("off");
    int[] _jspx_push_body_count_form_005finput_005f17 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f17 = _jspx_th_form_005finput_005f17.doStartTag();
      if (_jspx_th_form_005finput_005f17.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f17[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f17.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f17.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fpattern_005fpath_005fautocomplete_005fnobody.reuse(_jspx_th_form_005finput_005f17);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f18(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f18 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f18.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f18.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/jsp/nurse/create-nurse.jsp(108,35) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f18.setPath("personInfo.addresses[1].address");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(108,35) null
    _jspx_th_form_005finput_005f18.setDynamicAttribute(null, "value", "Espanya Blvd.");
    int[] _jspx_push_body_count_form_005finput_005f18 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f18 = _jspx_th_form_005finput_005f18.doStartTag();
      if (_jspx_th_form_005finput_005f18.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f18[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f18.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f18.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005fpath_005fnobody.reuse(_jspx_th_form_005finput_005f18);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f19(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f19 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f19.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f19.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/jsp/nurse/create-nurse.jsp(109,32) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f19.setPath("personInfo.addresses[1].city");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(109,32) null
    _jspx_th_form_005finput_005f19.setDynamicAttribute(null, "value", "Manila");
    int[] _jspx_push_body_count_form_005finput_005f19 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f19 = _jspx_th_form_005finput_005f19.doStartTag();
      if (_jspx_th_form_005finput_005f19.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f19[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f19.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f19.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005fpath_005fnobody.reuse(_jspx_th_form_005finput_005f19);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f20(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f20 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f20.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f20.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/jsp/nurse/create-nurse.jsp(110,36) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f20.setPath("personInfo.addresses[1].province");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(110,36) null
    _jspx_th_form_005finput_005f20.setDynamicAttribute(null, "value", "Manila");
    int[] _jspx_push_body_count_form_005finput_005f20 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f20 = _jspx_th_form_005finput_005f20.doStartTag();
      if (_jspx_th_form_005finput_005f20.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f20[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f20.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f20.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005fpath_005fnobody.reuse(_jspx_th_form_005finput_005f20);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f21(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f21 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f21.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f21.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/jsp/nurse/create-nurse.jsp(111,36) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f21.setPath("personInfo.addresses[1].zipCode");
    // /WEB-INF/jsp/nurse/create-nurse.jsp(111,36) null
    _jspx_th_form_005finput_005f21.setDynamicAttribute(null, "value", "1015");
    int[] _jspx_push_body_count_form_005finput_005f21 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f21 = _jspx_th_form_005finput_005f21.doStartTag();
      if (_jspx_th_form_005finput_005f21.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f21[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f21.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f21.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fvalue_005fpath_005fnobody.reuse(_jspx_th_form_005finput_005f21);
    }
    return false;
  }
}
